### ISSUE TITLE
Few improvement ideas

### ISSUE THREAD

**Issue by caemor** [DeveloperPaul123/modern-cv#12]
- Accept other languages (mainly regarding "Resume" at the bottom of the document)
- Don't show icons & text if github,phone,... is set to none
- Allow color changes

**Comment by DeveloperPaul123** [comment]
Hi 👋 thanks for the suggestions!

> Allow color changes

It's already possible to select the accent color when using the template.

> Accept other languages (mainly regarding "Resume" at the bottom of the document)

Yes this is something I definitely want to do!

> Don't show icons & text if github,phone,... is set to none

Just to make sure I understand, are you talking about the text and icons in the heading of the document?

**Comment by bluen** [comment]
For the moment this works for me to replace the "Résumé" at the bottom with the German "Lebenslauf", and the the accent_color to "red" for everything except the 'secondary-right-header' which always seems to use the 'default-accent-color'.

```
#import "@preview/modern-cv:0.1.0": *

#show "Résumé": "Lebenslauf"

#let accent-color = red
#show: resume.with(
  accent_color: accent-color,
 ...
)
...
```

**Comment by DeveloperPaul123** [comment]
> 'secondary-right-header' which always seems to use the 'default-accent-color'

Thanks for reporting this, see #19 for further tracking.

**Comment by DeveloperPaul123** [comment]
See also #18 for further language support
