### ISSUE TITLE
Add more info in usage

### ISSUE THREAD

**Issue by jjscaria** [DeveloperPaul123/modern-cv#2]
Can you please add more info on how to use the code for people that are not familiar with typst? 
What to install?
What format the file needs to be?
What commands to use to compile the code? etc.

**Comment by DeveloperPaul123** [comment]
Sure thing! I can definitely do this. Thanks for the feedback

**Comment by DeveloperPaul123** [comment]
Let me know if there's anything else you feel is missing from the README
