### ISSUE TITLE
[Feature Request] Entry Subtitle Stacking

### ISSUE THREAD

**Issue by jaimehrubiks** [DeveloperPaul123/modern-cv#21]
First of all thanks for sharing this CV template, it's really good.

In this post I suggest the ability to add multiple sub-entries for each entry. This could be used for something like "Title Stacking" (adding multiple titles from the same company).

This can be achieved right now by not specifying the title and location on the second resume-entry item, **however**, the line is still added as a blank space, so it doesn't look good.

```
#resume-entry(
  title: "Job Title",
  location: "Chicago, US",
  date: "2019 - Present",
  description: "Engineer"
)

#resume-item[
  - #lorem(20)
]

#resume-entry(
  date: "2011 - 2019",
  description: "Intern"
)

#resume-item[
  - #lorem(20)
]
```

I assume there are other ways to achieve the same result, I don't know much about typst

**Comment by DeveloperPaul123** [comment]
> First of all thanks for sharing this CV template, it's really good.

Thanks! Appreciate that.

I think I understand your request. Would something like this suffice?

![image](https://github.com/DeveloperPaul123/modern-cv/assets/6591180/544b060c-26d1-4684-b1d2-151142a6a5b7)

If so you can achieve that by using one of the helper functions that is used internally by `#resume-entry`

```typst
= Experience

#resume-entry(
  title: "Job Title",
  location: "Chicago, US",
  date: "2019 - Present",
  description: "Engineer"
)

#resume-item[
  - #lorem(20)
]

#secondary-justified-header(
  "Intern",
  "2017 - 2019"
)

#resume-item[
  - #lorem(20)
]
```

**Comment by jaimehrubiks** [comment]
Yes, that is exactly what I was looking for! Thanks!
