### ISSUE TITLE
Emojis are not shown. 

### ISSUE THREAD

**Issue by Kangarooss** [DeveloperPaul123/modern-cv#26]
<img width="557" alt="image" src="https://github.com/DeveloperPaul123/modern-cv/assets/127260537/00e8e5e9-3198-4e15-89ae-b7da57021516">

Emojis are not shown in Typst web app.

**Comment by DeveloperPaul123** [comment]
Have you installed the required fonts?

**Comment by Kangarooss** [comment]
> Have you installed the required fonts?

<img width="841" alt="image" src="https://github.com/DeveloperPaul123/modern-cv/assets/127260537/9d9483d2-8c5a-4324-ad1f-c2878faae597">

I am using offical web app.

**Comment by DeveloperPaul123** [comment]
And you're using the latest version of the template?

**Comment by DeveloperPaul123** [comment]
Actually, you _do_ need to install the font awesome fonts, even in the web app. This is right after the snippet you posted 
![image](https://github.com/DeveloperPaul123/modern-cv/assets/6591180/a39dcaca-68c2-4723-a781-6992cc4c636e)

**Comment by Kangarooss** [comment]
Ok. If I understand it correctly, this is a problem of Typst, whose package manager does not handle fonts.

**Comment by DeveloperPaul123** [comment]
typst does handle fonts, it just won't auto install them for you. And I don't know of a way to bundle the fonts with the template when you use it on the web app.

**Comment by Kangarooss** [comment]
Thanks a lot.
