### ISSUE TITLE
Add option(s) to override or remove the footer in the resume

### ISSUE THREAD

**Issue by DeveloperPaul123** [DeveloperPaul123/modern-cv#32]
As mentioned in the title, is there anyway to override or remove the footer in the resume ?
![image](https://github.com/DeveloperPaul123/modern-cv/assets/22954311/bda858b1-228e-4c14-b4df-ddd2922275b6)

The page number doesn't make a lot of sense since it's only one page anyway.

Best regards

_Originally posted by @LucasGenoud in https://github.com/DeveloperPaul123/modern-cv/discussions/31_

**Comment by kir0ul** [comment]
Any news about this option?

**Comment by DeveloperPaul123** [comment]
This is a WIP

**Comment by DeveloperPaul123** [comment]
Fixed in #55 

@kir0ul can you take a look at the PR and see if this would suffice?

**Comment by kir0ul** [comment]
> Fixed in #55
> 
> @kir0ul can you take a look at the PR and see if this would suffice?

Sorry, coming back to this only now. I tested directly with v0.6.0, and it looks perfect for my needs, thanks!

I made a quick PR: https://github.com/DeveloperPaul123/modern-cv/pull/62, as I got bitten by the README and template that still load v.0.5.0 where the `show-footer` option doesn't work.

**Comment by DeveloperPaul123** [comment]
> > Fixed in #55
> > @kir0ul can you take a look at the PR and see if this would suffice?
> 
> Sorry, coming back to this only now. I tested directly with v0.6.0, and it looks perfect for my needs, thanks!
> 
> I made a quick PR: #62, as I got bitten by the README and template that still load v.0.5.0 where the `show-footer` option doesn't work.

Glad to hear that! Sorry about the README, it seems that I keep forgetting that :sweat_smile: . Thanks!
