### ISSUE TITLE
`#resume-entry` does not scale

### ISSUE THREAD

**Issue by TomVer99** [DeveloperPaul123/modern-cv#35]
I have a `#resume-entry` where I only use `title` and `date`. But the entry takes up quite a bit of height.

![image](https://github.com/DeveloperPaul123/modern-cv/assets/66320357/5786d705-6575-43fa-8100-161ae5b85a78)

```typst
#resume-entry(
  title: "TEXT",
  date: "DATE",
)
```

I expected it to collapse in some way.

**Comment by DeveloperPaul123** [comment]
Hmm I'm currently on mobile so I'm not 100% sure, but I think the fields `title` and `location` should appear on the same line. Same for `position` and `date`. 

Basically the fields are set up in 2 columns and 2 rows.

**Comment by TomVer99** [comment]
> Hmm I'm currently on mobile so I'm not 100% sure, but I think the fields `title` and `location` should appear on the same line. Same for `position` and `date`. 
> 
> Basically the fields are set up in 2 columns and 2 rows. 

It could he nice that if only 2 fields are populated, it would be 2 columns but 1 row, now there is some odd white space when only 2 are used (in specific combinations).

**Comment by DeveloperPaul123** [comment]
While it would be nice, I think it's beyond the scope of `resume-header` to adapt in this way, based solely on the number of inputs given. 

I think the best alternative would be to use the helper functions that `resume-entry` is using internally to get your desired output. 

See `#justified-header()` and `#secondary-justified-header()`
