### ISSUE TITLE
Remove space between name in chinese (zh)

### ISSUE THREAD

**Issue by pickfire** [DeveloperPaul123/modern-cv#37]
Chinese texts does not really use space, so would be good to remove it between the first name and last name.

![image](https://github.com/DeveloperPaul123/modern-cv/assets/4687791/8a1d6e45-6fb7-4d1b-bf85-bcb65c832112)

I believe japanese (ja) would need to do the same too.

**Comment by DeveloperPaul123** [comment]
Interesting, thanks for pointing that out!

**Comment by DeveloperPaul123** [comment]
@pickfire would you be able to provide sample text I can use to test this out? Also text for the lang.toml would be good too. You could do that here or file a PR if you're willing. 

Thanks!

**Comment by DeveloperPaul123** [comment]
Is it typical to do lastname + firstname in chinese/japanese?

**Comment by DeveloperPaul123** [comment]
@pickfire Can you look at #40 and see if this addresses this issue?

**Comment by DeveloperPaul123** [comment]
If you have issues, just re-open the issue.
