### ISSUE TITLE
A little problem with the Russian language

### ISSUE THREAD

**Issue by Blezz-tech** [DeveloperPaul123/modern-cv#38]
But there is a small problem with the fact that in Russian language different endings are written for different genera.

What I mean is

English -> Russian
Dear Sir -> Уважаемый сэр
Dear Madame -> Уважаемая мадам

Dear Sir/Madame -> Уважаемый/ая сэр/мадам

So we need to give an optional option to override the "dear" variable.

Will do that a little later and send a pull requset

(Translated with a little help from Deep. Excuse me)

**Comment by DeveloperPaul123** [comment]
Interesting, thanks for explaining that!

**Comment by DeveloperPaul123** [comment]
Fixed in #39
