### ISSUE TITLE
Bibliography section

### ISSUE THREAD

**Issue by hadim** [DeveloperPaul123/modern-cv#44]
Thanks for this great template.

Is there is a way to add a biblio section?

**Comment by DeveloperPaul123** [comment]
Do you mean like publications or things you have written? I have something similar to this in my resume:

![image](https://github.com/DeveloperPaul123/modern-cv/assets/6591180/5413ef67-3666-448a-8d68-5c110770a96a)

```typst
= Publications

#resume-entry(
  title: lorem(20),
  location: "American Association of Physicists in Medicine",
  date: "2019",
  description: "Role"
)

#resume-item[
  - Item 1 #lorem(12)
  - Item 2 #lorem(14)
]

#resume-entry(
  title: lorem(15),
  location: "Medical Physics",
  date: "2023",
  description: "Role"
)

#resume-item[
  - Did xyz #lorem(12)
  - Did xzy #lorem(10)
]

```

**Comment by hadim** [comment]
I was thinking something based on a .bib file but indeed what you propose will do the job. Thank you!
