### ISSUE TITLE
Add twitter and google scholar links with icons in the header

### ISSUE THREAD

**Issue by hadim** [DeveloperPaul123/modern-cv#45]
This is possible with the https://github.com/posquit0/Awesome-CV latex template and I wonder whether this is possible for this template as well?

Can I do that within the resume.typ file from the webapp or do I need to clone and edit the moder-cv template?

**Comment by hadim** [comment]
Maybe same question for the birthdate that is possible to add with the latex template.

**Comment by DeveloperPaul123** [comment]
I think it should be possible to add twitter and google scholar links in the header. Not sure about birthdate though. Also, I don't see that on the Awesome-CV template. Can you post an example?

**Comment by hadim** [comment]
It might be me who added it a long time ago now.

**Comment by hadim** [comment]
I made a PR with a few changes needed for myself in case it's helpful https://github.com/DeveloperPaul123/modern-cv/pull/46

**Comment by DeveloperPaul123** [comment]
Resolved in #46
