### ISSUE TITLE
Is it possible to customize the font used

### ISSUE THREAD

**Issue by gtn1024** [DeveloperPaul123/modern-cv#50]
<img width="163" alt="image" src="https://github.com/user-attachments/assets/46de385e-6081-480a-961a-bbc2ef336bcf">

<img width="158" alt="image" src="https://github.com/user-attachments/assets/863b4c1d-2666-4f4c-9399-d8260f02274a">

The default font is not very good for Chinese, can we provide an option to customize it.
Or can only modify `lib.typ` file?

**Comment by gtn1024** [comment]
Great, thanks!

**Comment by AceofSpades5757** [comment]
Looks like you can also use `set` to change this after the `show`.

```typst
#show: coverletter.with(
  ...,
)
#set text(
  font: "New Computer Modern",
  size: 10pt
)

```

**Comment by gtn1024** [comment]
@AceofSpades5757 seems great to this solution. It do work!
