### ISSUE TITLE
Error when using `show-footer: false`

### ISSUE THREAD

**Issue by mgrimace** [DeveloperPaul123/modern-cv#57]
Hello, 
I'd like to hide the footer, and if I include the `show-footer: false` line from the template:
```
  date: datetime.today().display(),
  language: "en",
  colored-headers: true,
  show-footer: false,
)
```
I receive the following error:
```bash
error: unexpected argument: show-footer
   ┌─ .../resume.typ:20:2
   │
20 │   show-footer: false,
   │   ^^^^^^^^^^^^^^^^^^
```

**Comment by mgrimace** [comment]
removing the line compiles the resume as expected

**Comment by DeveloperPaul123** [comment]
This hasn't been put into a formal release yet. This will be available soon in `0.6.0`

**Comment by mgrimace** [comment]
> This hasn't been put into a formal release yet. This will be available soon in `0.6.0`

My bad, I didn't catch that. I see you just released 0.6.0 and I'll try that out. Do I just change from `#import "@preview/modern-cv:0.5.0": *` to `#import "@preview/modern-cv:0.6.0": *` on my template?

**Comment by DeveloperPaul123** [comment]
@mgrimace No worries! Sorry for the delay, once this PR is merged, it will be available on typst universe as well https://github.com/typst/packages/pull/934. I was going to mention the local option as a temporary workaround. Thanks!

**Comment by mgrimace** [comment]
Thanks again, and no need to apologize, this was me stumbling through how typst functions and some of the quirks. Thanks so much for all your work here!

**Comment by DeveloperPaul123** [comment]
For sure! Thanks for using the template 😁
