### ISSUE TITLE
[Feature Request] Add personal website section

### ISSUE THREAD

**Issue by osbm** [DeveloperPaul123/modern-cv#59]
Adding clickable personal website section as an author attribution would be awesome. Is it feasible?

**Comment by osbm** [comment]
Thanks for the awesome work by the way. ❤️❤️❤️❤️

**Comment by DeveloperPaul123** [comment]
Yes this is certainly possible! Just to be clear, you would want this at the top of the resume or coverletter right? Where the phone number and other "author" information is?

**Comment by osbm** [comment]
Yes right, that would be awesome :)

**Comment by DeveloperPaul123** [comment]
@osbm Would https://github.com/DeveloperPaul123/modern-cv/pull/64 work for you?

**Comment by osbm** [comment]
Yes this is is awesome. Thanks for fast work :100: 

I also want to mention how i tried out this feature. For future reference for me. :)

Normally i do this:

```typst
#import "@preview/modern-cv:0.6.0": *

....
```

First clone the new branch to local typst packages folder:

```bash
$ git clone --single-branch --branch feature/personal-website https://github.com/DeveloperPaul123/modern-cv.git ~/.local/share/typst/packages/local/modern-cv/0.7.0
```

Now i can test this version with:

```typst
#import "@local/modern-cv:0.7.0": *


...
```

**Comment by DeveloperPaul123** [comment]
Great! I'll merge it in. 

As a side note, you can clone the repo locally and then run the script `scripts/package @preview` and this will install the package locally on your machine under the standard `preview` folder so you can import it like normal.

**Comment by osbm** [comment]
Thats neat. I dont know how i missed that

**Comment by DeveloperPaul123** [comment]
I just added it yesterday :)
