### ISSUE TITLE
FA icons are not displayed

### ISSUE THREAD

**Issue by JKRhb** [DeveloperPaul123/modern-cv#6]
Hi! Thank you for the awesome (no pun intended) template! :)

While trying out the template in the web app via Typst universe, I noticed that the font awesome icons are currently not being rendered:

<img width="630" alt="image" src="https://github.com/DeveloperPaul123/modern-cv/assets/12641361/f4cd6544-7cc5-4ce0-a7d8-6414efc9d2f6">

**Comment by DeveloperPaul123** [comment]
Hello! Thanks for using it!

This is likely due to fontawesome not being installed. Do you have those fonts installed? You only need the free version found here https://fontawesome.com/download

If you don't want to install them, you can also set the font directory for typst when you compile your `*.typ` files with 

```bash
typst --font-path <font directory> compile resume.typ
```

Internally, the template is using this package to show font awesome icons https://typst.app/universe/package/fontawesome.

Hope that helps!

**Comment by DeveloperPaul123** [comment]
Just pushed some updates to the README that hopefully will make all this more clear.

**Comment by JKRhb** [comment]
Ah, thank you! I was just trying it out via the web app and expected the icons to just show up – makes sense that you need to have Font Awesome installed first :) Thank you for updating the README, that makes things a lot clearer! :)

**Comment by DeveloperPaul123** [comment]
No problem! Thanks for reporting the issue :)

**Comment by Joelius300** [comment]
I'm having the same issue. I installed the fonts and it seems that Typst recognizes them. Running `typst fonts --variants` and scrolling up to the Font Awesome fonts gives shows the following.

```
Font Awesome 5 Brands
- Style: Normal, Weight: 400, Stretch: FontStretch(1000)
Font Awesome 5 Free
- Style: Normal, Weight: 400, Stretch: FontStretch(1000)
Font Awesome 5 Free Solid
- Style: Normal, Weight: 900, Stretch: FontStretch(1000)
```

What am I missing?

**Comment by JKRhb** [comment]
Hmm, could it be that the template only works with Font Awesome 6 and not with version 5?

**Comment by Joelius300** [comment]
Hm maybe. You got it to work right? Could you show me your output of `typst fonts --variants`? I installed fontawesome by linking from `texlive-fontsextra` as opposed to manual installation, maybe that only installed outdated versions.

**Comment by johentsch** [comment]
Hi, thanks for porting Awesome CV to typst!! Looking forward to using it. As a newcomer, I wonder whether it's realistic that we'll be able to use Awesome Font in the Typst WebApp, too?

**Comment by DeveloperPaul123** [comment]
> Hi, thanks for porting Awesome CV to typst!! Looking forward to using it. As a newcomer, I wonder whether it's realistic that we'll be able to use Awesome Font in the Typst WebApp, too?

Hi @johentsch 

Yes this should be possible. You can download fontawesome 6 and put it in a folder in your typst.app project. Name the folder `font` or `fonts` ( I can't remember which is correct ) and place the font files in there.

**Comment by johentsch** [comment]
Ah damn I should have read the README, duh, sorry for the redundant question. It works like a charm!
