### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by reknih** [DeveloperPaul123/modern-cv#69]
Hey there,

this URL shows up as a 404 broken link in our checks:

- https://typst.app/docs/reference/types/dictionary/

It would be great if you could update it.

**Comment by DeveloperPaul123** [comment]
Hello! 

Sorry, but I'm a bit confused. Where is that link in the README?

I just checked all the links in the document and only found 1 that was broken with regard to installing the typst CLI. (see d12482c7fee4c8303f3d4df7665fea1bd182b7d2). I didn't see any references to typst dictionary documentation.

**Comment by reknih** [comment]
nvm it was that link. I did not check whether the main readme differs from the release on Universe.
