### ISSUE TITLE
typst 0.12 -  just minor changes necessary?

### ISSUE THREAD

**Issue by bluen** [DeveloperPaul123/modern-cv#70]
In order to get rid of some warnings when using modern-cv (0.6.0) with typst 0.12.0 (released yesterday) I tried the following local changes:
```
diff --git a/lib.typ b/lib.typ
index 1ce2982..7a6932e 100644
--- a/lib.typ
+++ b/lib.typ
@@ -104,7 +104,9 @@
       #linguify("resume", from: lang_data)
     ]
   ][
-    #counter(page).display()
+    #context {
+      counter(page).display()
+    }
   ]
 }

@@ -228,11 +230,7 @@
   )

   // set paragraph spacing
-  show par: set block(
-    above: 0.75em,
-    below: 0.75em,
-  )
-  set par(justify: true)
+  set par(spacing: 0.75em, justify: true)

   set heading(
     numbering: none,
diff --git a/scripts/uninstall b/scripts/uninstall
old mode 100644
new mode 100755
```

That seems to work as expected - but the tests fail:
```
> just test
typst-test run
  Running tests
      failed resume
             Page 1 did not match
                hint: Diff images have been saved at '/Users/jurgenkleer/Documents/modern-cv/tests/resume/diff'
      failed utilities
             Page 1 did not match
                hint: Diff images have been saved at '/Users/jurgenkleer/Documents/modern-cv/tests/utilities/diff'

  Summary
    0 / 2 passed.
error: Recipe `test` failed on line 15 with exit code 1
```
It looks like the rendered output is slightly different:

![1](https://github.com/user-attachments/assets/f052b83d-ef3c-4d60-a1cf-cfd613b593c8)

![1](https://github.com/user-attachments/assets/9380383e-54fc-4358-be46-07351e0044a8)

If that's expected or tolerable I'd be happily opening a PR

**Comment by DeveloperPaul123** [comment]
That's likely to be expected with the major changes that were made. Feel free to go ahead and file a PR and I can double check things as part of the review process. Thanks so much!
